{% set name = "openfe" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/openfe/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bfac51d310dfbfa47ad03fc722d26c636b51375ee768acd34c095a5a7df6b892

build:
  noarch: python
  number: 0
  entry_points:
    - openfe = openfecli.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - click
    - lomap2 >=2.1.0
    - networkx
    - numpy <1.24.0
    - openff-toolkit
    - plugcli
    - python >=3.9
    - rdkit
    - typing-extensions
    - gufe ==0.7.*
    - pydantic
    - openff-units
    - openff-toolkit
    - openmmforcefields >=0.11.2
    - openmmtools
    - openmm
    - libnetcdf <4.9

test:
  imports:
    - openfe
  requires:
    - pip
  commands:
    - pip check
    - openfe --help

about:
  home: https://github.com/OpenFreeEnergy/openfe
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alchemical free energy calculations for the masses.
  description: |
    The Open Free Energy (OpenFE) project is dedicated to the development 
    of open source tools for binding free energy calculations to guide 
    pharmaceutical drug design and discovery.
  doc_url: https://openfe.rtfd.io/
  dev_url: https://github.com/OpenFreeEnergy/openfe

extra:
  recipe-maintainers:
    - mikemhenry
    - richardjgowers
    - IAlibay
    - dwhswenson
