{% set name = "openfe" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/openfe/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f1967fcdd46976ecc46c95dab4e21e2cd813004a2ce8d9793ba2f3fb625bee77

build:
  noarch: python
  number: 1
  entry_points:
    - openfe = openfecli.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - click
    - lomap2 >=2.1.0
    - networkx
    - numpy
    - openff-toolkit
    - plugcli
    - python >=3.9
    - rdkit
    - typing-extensions
    - gufe ==0.5
    - pydantic
    - openff-units ==0.1.8
    - openff-toolkit ==0.11.2
    - openmmforcefields >=0.11.2
    - openmmtools
    - openmm

test:
  imports:
    - openfe
  requires:
    - pip
  commands:
    - pip check
    - openfe --help

about:
  home: https://github.com/OpenFreeEnergy/openfe
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alchemical free energy calculations for the masses.
  description: |
    The Open Free Energy (OpenFE) project is dedicated to the development 
    of open source tools for binding free energy calculations to guide 
    pharmaceutical drug design and discovery.
  doc_url: https://openfe.rtfd.io/
  dev_url: https://github.com/OpenFreeEnergy/openfe

extra:
  recipe-maintainers:
    - mikemhenry
    - richardjgowers
    - IAlibay
    - dwhswenson
